baseURL = "https://matejv.com/"
languageCode = "en-us"
title = "matejv"
copyright="Made with ❤."

theme = "hugo-bearblog-fork"

[markup.goldmark.renderer]
  unsafe= true

[params]
  hideMadeWithLine=true


[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "Recommendations"
url = "/recommendations"
weight = 3
