baseURL = "https://matejv.com/"
languageCode = "en-us"
title = "Matejov blog"
theme = "archie"

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
